server/routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Auth\SocialAuthFacebookController;
use App\Http\Controllers\Auth\SocialAuthGoogleController;
use Illuminate\Support\Facades\Route;
use App\Models\Category;
use App\Models\Article;
use App\Models\Author;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\RedirectController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CallbackController;
use App\Http\Controllers\ComplaneController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\RatingController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('/content/main', ["pageTitle" => "Main"]);
})->name('main');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//
//Route::get("/category/{id?}", function () {
//    return view("/content/category", ["pageTitle" => "Category"]);
//})->name("blog");
//
////Route::get("/categories", function () {
////    return view("/content/categories", ["pageTitle" => "Categories"]);
////});
//
//Route::get("/article/{id?}", function () {
//    return view("/content/article", ["pageTitle" => "Article"]);
//});
//
//Route::get("/author/{id?}", function () {
//    return view("/content/author", ["pageTitle" => "Author"]);
//});

Route::prefix('profile')->group(function () {
    Route::view('/', "forms.form_name_phone")->name("profile.index");
    Route::post('/save', [ProfileController::class, 'create'])->name("profile.create");
    Route::get('/read', [ProfileController::class, 'read'])->name("profile.show");
    Route::post('/update', [ProfileController::class, 'update'])->name("profile.store");
    Route::post('/delete', [ProfileController::class, 'delete'])->name("profile.destroy");
});


Route::prefix('callback')->group(function () {
    Route::view('/', "forms.callback",)->name("callback.index");
    Route::post('/save', [CallbackController::class, 'create'])->name("callback.create");
    Route::post('/delete', [CallbackController::class, 'delete'])->name("callback.destroy");
});

Route::prefix('complain')->group(function () {
    Route::view('/', "forms.complain")->name("complain.index");
    Route::post('/save', [ComplaneController::class, 'create'])->name("complain.create");
    Route::post('/delete', [ComplaneController::class, 'delete'])->name("complain.destroy");
});

Route::prefix('comment/')->group(function() {
    Route::view('/{id?}', "forms.comment")->name("comment.index");
    Route::post('/save', [CommentController::class, 'create'])->name("comment.create");
    Route::post('/delete', [CommentController::class, 'delete'])->name("comment.destroy");
});
Route::prefix('rating')->group(function () {
    Route::view('/{id?}', "forms.rating")->name("rating.index");
    Route::post('/save', [RatingController::class, 'create'])->name("rating.create");
});

Route::resource('admin/categories', CategoryController::class );

Route::resource('admin/articles', ArticleController::class );


Route::prefix("/auth")->group(function (){
    Route::get('/facebook/redirect', [SocialAuthFacebookController::class, 'redirect'])->name("facebook");
    Route::get('/facebook/callback', [SocialAuthFacebookController::class, 'callback']);

    Route::get('/google/redirect', [SocialAuthGoogleController::class, 'redirectToProvider'])->name("google");
    Route::get('/google/callback', [SocialAuthGoogleController::class, 'handleProviderCallback']);

});

server/app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ["title", "description", "text", "is_active", 'slug'];

//    public function category()
//    {
//        return $this->belongsToMany(Category::class, "categories_has_articles");
//    }
}

server/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FormArticleRequest;
use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::get();
        return view("articles.articles", compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("articles.article_create");

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormArticleRequest $request)
    {

        Article::create($request->all());
        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view("articles.article_show", compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view("articles.article_update", compact('article'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(FormArticleRequest $request, Article $article)
    {
        $article->update($request->all());
        return redirect()->route('articles.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('articles.index');
    }
}

server/resources/views/articles/article_create.blade.php
@extends("layouts.compose")
@section("content")
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">

        <div class="col-md-6 px-0">
            <form method="post" action="{{route('articles.store')}}">
                @csrf
                <div class="form-group col-md-15">
                    <label for="inputTitle">Title</label>
                    @error('title')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="title" class="form-control" id="inputTitle" value="{{old('title')}}">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputDescription">Description</label>
                    @error('description')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="description" class="form-control" id="inputDescription" value="{{old('description')}}">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputArticle">Article</label>
                    @error('text')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <textarea name="text" class="form-control" style="height: 150px" id="inputArticle" value="{{old('text')}}" rows="10"></textarea>
                </div>
                <div class="form-group col-md-15">
                    <label for="inputSlug">Slug</label>
                    @error('slug')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="slug" class="form-control" id="inputSlug" value="{{old('slug')}}">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputIsActive">Is active</label>
                    @error('is_active')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="is_active" class="form-control" id="inputIsActive" value="{{old('is_active')}}">
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button class="btn btn-primary"><a href="{{route('articles.index')}}">Cancel</a></button>
                </div>
            </form>


        </div>
    </div>
@endsection

server/resources/views/articles/article_show.blade.php
@extends("layouts.compose")
@section("content")
<div class="row mb-2">
    <h1>Article {{$article->title}}</h1>
    <h2>Description: {{$article->description}}</h2>
    <p>{{$article->text}}</p>
    @auth
        <div>
            <button  class="btn btn-primary"><a href="{{route('articles.edit', $article->id)}}">Edit</a></button>
        </div>
    @endauth
</div>
@endsection

server/resources/views/articles/article_update.blade.php
@extends("layouts.compose")
@section("content")
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <form method="post" action="{{route('articles.update', $article)}}">
                @csrf
                @method('PUT')
                <div class="form-group col-md-15">
                    <label for="inputTitle">Title</label>
                    @error('title')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="title" value="{{$article->title}}" class="form-control" id="inputTitle">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputDescription">Description</label>
                    @error('description')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="description" value="{{$article->description}}" class="form-control"
                           id="inputDescription">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputArticle">Article</label>
                    @error('text')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <textarea name="text" value="" class="form-control" style="height: 150px" id="inputArticle" rows="10">{{$article->text}}</textarea>
                </div>
                <div class="form-group col-md-15">
                    <label for="inputSlug">Slug</label>
                    @error('slug')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="slug" value="{{$article->slug}}" class="form-control" id="inputSlug">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputIsActive">Is active</label>
                    @error('is_active')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="is_active" value="{{$article->is_active}}" class="form-control" id="inputIsActive">
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>

            @if(Auth::user()->isAdmin())
            <form class="mt-3" method="post" action="{{route('articles.destroy', $article)}}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
            @endif

            <div>
                <button class="btn btn-primary mt-3"><a href="{{route('articles.index')}}">Cancel</a></button>
            </div>
        </div>
    </div>
@endsection

server/resources/views/articles/articles.blade.php
@extends("layouts.compose")
@section("content")
    <div class="row mb-2">
        <h1>Articles</h1>
        <ul class="list-group">
            @foreach($articles as $article)
                <li class="list-group-item"><a href="{{route('articles.show', $article->id)}}">{{$article->title}}</a></li>
            @endforeach
        </ul>
        @auth
            <div class="pt-5">
                <buttom class="btn btn-primary"><a href="{{route('articles.create')}}">New article</a></buttom>
            </div>
        @endauth
    </div>
@endsection