server/routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Auth\SocialAuthFacebookController;
use App\Http\Controllers\Auth\SocialAuthGoogleController;
use Illuminate\Support\Facades\Route;
use App\Models\Category;
use App\Models\Article;
use App\Models\Author;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\RedirectController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CallbackController;
use App\Http\Controllers\ComplaneController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\RatingController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('/content/main', ["pageTitle" => "Main"]);
})->name('main');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//
//Route::get("/category/{id?}", function () {
//    return view("/content/category", ["pageTitle" => "Category"]);
//})->name("blog");
//
////Route::get("/categories", function () {
////    return view("/content/categories", ["pageTitle" => "Categories"]);
////});
//
//Route::get("/article/{id?}", function () {
//    return view("/content/article", ["pageTitle" => "Article"]);
//});
//
//Route::get("/author/{id?}", function () {
//    return view("/content/author", ["pageTitle" => "Author"]);
//});

Route::prefix('profile')->group(function () {
    Route::view('/', "forms.form_name_phone")->name("profile.index");
    Route::post('/save', [ProfileController::class, 'create'])->name("profile.create");
    Route::get('/read', [ProfileController::class, 'read'])->name("profile.show");
    Route::post('/update', [ProfileController::class, 'update'])->name("profile.store");
    Route::post('/delete', [ProfileController::class, 'delete'])->name("profile.destroy");
});


Route::prefix('callback')->group(function () {
    Route::view('/', "forms.callback",)->name("callback.index");
    Route::post('/save', [CallbackController::class, 'create'])->name("callback.create");
    Route::post('/delete', [CallbackController::class, 'delete'])->name("callback.destroy");
});

Route::prefix('complain')->group(function () {
    Route::view('/', "forms.complain")->name("complain.index");
    Route::post('/save', [ComplaneController::class, 'create'])->name("complain.create");
    Route::post('/delete', [ComplaneController::class, 'delete'])->name("complain.destroy");
});

Route::prefix('comment/')->group(function() {
    Route::view('/{id?}', "forms.comment")->name("comment.index");
    Route::post('/save', [CommentController::class, 'create'])->name("comment.create");
    Route::post('/delete', [CommentController::class, 'delete'])->name("comment.destroy");
});
Route::prefix('rating')->group(function () {
    Route::view('/{id?}', "forms.rating")->name("rating.index");
    Route::post('/save', [RatingController::class, 'create'])->name("rating.create");
});

Route::resource('admin/categories', CategoryController::class );

Route::resource('admin/articles', ArticleController::class );


Route::prefix("/auth")->group(function (){
    Route::get('/facebook/redirect', [SocialAuthFacebookController::class, 'redirect'])->name("facebook");
    Route::get('/facebook/callback', [SocialAuthFacebookController::class, 'callback']);

    Route::get('/google/redirect', [SocialAuthGoogleController::class, 'redirectToProvider'])->name("google");
    Route::get('/google/callback', [SocialAuthGoogleController::class, 'handleProviderCallback']);

});

server/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ["category", "description", "is_active", 'slug'];

//    public function article()
//    {
//        return $this->belongsToMany(Article::class, "categories_has_articles");
//    }

}

server/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\FormCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
 //     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::get();
        return view("categories.categories",compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
 //     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("categories.category_create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
//     * @return \Illuminate\Http\Response
     */
    public function store(FormCategoryRequest $request, Category $category)
    {
        Category::create($request->all());
        return redirect()->route('categories.index');

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Category $category
 //     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view("categories.category_show", compact('category'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Category $category
 //     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view("categories.category_update", compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Category $category
     //     * @return \Illuminate\Http\Response
     */
    public function update(FormCategoryRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Category $category
//     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('categories.index');
    }


}

server/resources/views/categories/categories.blade.php
@extends("layouts.compose")
@section("content")
<div class="row mb-2">
    <h1>Categories</h1>
    <ul class="list-group">
        @foreach($categories as $category)
            <li class="list-group-item"><a href="{{route('categories.show', $category->id)}}">{{$category->category}}</a></li>
        @endforeach
    </ul>
    @auth
        <div class="pt-5">
            <buttom class="btn btn-primary"><a href="{{route('categories.create')}}">New category</a></buttom>
        </div>
    @endauth

</div>
@endsection

server/resources/views/categories/category_create.blade.php
@extends("layouts.compose")
@section("content")
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <form method="post" action="{{route('categories.store')}}">
            @csrf
            <div class="form-group col-md-15">
                <label for="inputCategory">Category</label>
                @error('category')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
                <input name="category" class="form-control" id="inputCategory" value="{{old('category')}}">
            </div>
            <div class="form-group col-md-15">
                <label for="inputDescription">Description</label>
                @error('description')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
                <input name="description" class="form-control" id="inputDescription" value="{{old('description')}}">
            </div>
            <div class="form-group col-md-15">
                <label for="inputSlug">Slug</label>
                @error('slug')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
                <input name="slug" class="form-control" id="inputSlug" value="{{old('slug')}}">
            </div>
            <div class="form-group col-md-15">
                <label for="inputIsActive">Is active</label>
                @error('is_active')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
                <input name="is_active" class="form-control" id="inputIsActive" value="{{old('is_active')}}">
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Save</button>
                <button  class="btn btn-primary"><a href="{{route('categories.index')}}">Cancel</a></button>
            </div>
        </form>


    </div>
</div>
@endsection

server/resources/views/categories/category_show.blade.php
@extends("layouts.compose")
@section("content")
<div class="row mb-2">
    <h1>Category</h1>

    <ul class="list-group">
        <li class="list-group-item">Category: {{$category->category}} </li>
        <li class="list-group-item">Description: {{$category->description}}</li>
    </ul>
    @auth
        <div>
            <button  class="btn btn-primary"><a href="{{route('categories.edit', $category->id)}}">Edit</a></button>
        </div>
    @endauth

</div>
@endsection

server/resources/views/categories/category_update.blade.php
@extends("layouts.compose")
@section("content")
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <form method="POST" action="{{route('categories.update', $category)}}">
                @csrf
                @method('PUT')
                <div class="form-group col-md-15">
                    <label for="inputCategory">Category</label>
                    @error('category')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="category" value="{{$category->category}}" class="form-control" id="inputCategory">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputDescription">Description</label>
                    @error('description')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="description" value="{{$category->description}}" class="form-control" id="inputDescription">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputSlug">Slug</label>
                    @error('slug')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="slug" value="{{$category->slug}}" class="form-control" id="inputSlug">
                </div>
                <div class="form-group col-md-15">
                    <label for="inputIsActive">Is active</label>
                    @error('is_active')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                    <input name="is_active" value="{{$category->is_active}}" class="form-control" id="inputIsActive">
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
            @if(Auth::user()->isAdmin())
                <form class="pt-3" method="post" action="{{route('categories.destroy', $category)}}">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-primary">Delete</button>
                </form>
            @endif


            <div>
                <button class="btn btn-primary mt-3"><a href="{{route('categories.index')}}">Cancel</a></button>
            </div>


        </div>
    </div>
@endsection